eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:  port: 8070
  
management:  endpoints:    web:      exposure:        include: "*"
        
spring:  application:    name: USER-SERVICE
  boot:    admin:      client:        url: http://localhost:9000